### ISSUE TITLE
Cannot reproduce active_learning.py with svgp model

### ISSUE THREAD

**Issue by cagoc** [wjmaddox/online_vargp#5]
When running
```python qnIPV_experiment.py --model=svgp```

```Traceback (most recent call last):
  File "..\online_vargp-main\experiments\active_learning\qnIPV_experiment.py", line 302, in <module>
    main(args)
  File "..\online_vargp-main\experiments\active_learning\qnIPV_experiment.py", line 229, in main
    candidates, acq_value = optimize_acqf(
                            ^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\botorch\optim\optimize.py", line 562, in optimize_acqf
    return _optimize_acqf(opt_acqf_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\botorch\optim\optimize.py", line 583, in _optimize_acqf
    return _optimize_acqf_batch(opt_inputs=opt_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\botorch\optim\optimize.py", line 274, in _optimize_acqf_batch
    batch_initial_conditions = opt_inputs.get_ic_generator()(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\botorch\optim\initializers.py", line 418, in gen_batch_initial_conditions
    Y_rnd_curr = acq_function(
                 ^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\botorch\utils\transforms.py", line 334, in decorated
    return method(cls, X, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\botorch\utils\transforms.py", line 288, in decorated
    output = method(acqf, X, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\botorch\acquisition\active_learning.py", line 96, in forward
    fantasy_model = self.model.fantasize(
                    ^^^^^^^^^^^^^^^^^^^^
  File "..\.conda\envs\env01\Lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'FixedNoiseVariationalGP' object has no attribute 'fantasize'
```
But it was successful with ```exact``` model.  Sorry for bothering but I how can I deal with?

**Comment by wjmaddox** [comment]
what versions of botorch and gpytorch are you using?

**Comment by cagoc** [comment]
I am very sorry for my late reply. I use botorch==0.11.1 and gpytorch==1.11. I have found that Botorch has not support Fantasize in Approximate GP model so far. Thus, qNIPV acqusition function is unavaliable unless I use exact GP-based model. This quite bother me.  I think this problem is related to Botorch. Thank you for your reply!
